import os
import django
from decimal import Decimal
from datetime import date

# Настройка Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'crm_system.settings')
django.setup()

from inventory.models import Brand, Model, ModelSpecification, ProductType, Warehouse, Product

def seed_db():
    Product.objects.all().delete()
    ModelSpecification.objects.all().delete()
    Model.objects.all().delete()
    Brand.objects.all().delete()
    ProductType.objects.all().delete()
    Warehouse.objects.all().delete()

    # Создание марок автомобилей
    brands = [
        {"name": "Toyota"},
        {"name": "Honda"},
        {"name": "BMW"},
        {"name": "Mercedes-Benz"},
        {"name": "Volkswagen"},
        {"name": "Ford"},
        {"name": "Hyundai"},
        {"name": "Audi"},
    ]
    for brand_data in brands:
        Brand.objects.get_or_create(name=brand_data["name"])

    # Создание моделей автомобилей
    models = [
        {"name": "Camry", "brand_name": "Toyota"},
        {"name": "Corolla", "brand_name": "Toyota"},
        {"name": "RAV4", "brand_name": "Toyota"},
        {"name": "Civic", "brand_name": "Honda"},
        {"name": "Accord", "brand_name": "Honda"},
        {"name": "CR-V", "brand_name": "Honda"},
        {"name": "X5", "brand_name": "BMW"},
        {"name": "3 Series", "brand_name": "BMW"},
        {"name": "5 Series", "brand_name": "BMW"},
        {"name": "C-Class", "brand_name": "Mercedes-Benz"},
        {"name": "E-Class", "brand_name": "Mercedes-Benz"},
        {"name": "Golf", "brand_name": "Volkswagen"},
        {"name": "Passat", "brand_name": "Volkswagen"},
        {"name": "Tiguan", "brand_name": "Volkswagen"},
        {"name": "F-150", "brand_name": "Ford"},
        {"name": "Mustang", "brand_name": "Ford"},
        {"name": "Tucson", "brand_name": "Hyundai"},
        {"name": "Sonata", "brand_name": "Hyundai"},
        {"name": "A4", "brand_name": "Audi"},
        {"name": "Q5", "brand_name": "Audi"},
    ]
    for model_data in models:
        brand = Brand.objects.get(name=model_data["brand_name"])
        Model.objects.get_or_create(name=model_data["name"], brand=brand)

    # Создание спецификаций моделей
    specs = [
        {"model_name": "Camry", "brand_name": "Toyota", "engine_capacity": 2.5, "engine_code": "A25A-FKS",
         "horsepower": 203, "production_start": date(2017, 6, 1), "production_end": None},
        {"model_name": "Camry", "brand_name": "Toyota", "engine_capacity": 3.5, "engine_code": "2GR-FKS",
         "horsepower": 301, "production_start": date(2017, 6, 1), "production_end": None},
        {"model_name": "Camry", "brand_name": "Toyota", "engine_capacity": 2.0, "engine_code": "6AR-FSE",
         "horsepower": 150, "production_start": date(2014, 9, 1), "production_end": date(2017, 5, 31)},
        {"model_name": "Corolla", "brand_name": "Toyota", "engine_capacity": 1.8, "engine_code": "2ZR-FE",
         "horsepower": 132, "production_start": date(2018, 3, 1), "production_end": None},
        {"model_name": "Corolla", "brand_name": "Toyota", "engine_capacity": 2.0, "engine_code": "M20A-FKS",
         "horsepower": 169, "production_start": date(2018, 3, 1), "production_end": None},
        {"model_name": "RAV4", "brand_name": "Toyota", "engine_capacity": 2.5, "engine_code": "A25A-FXS",
         "horsepower": 203, "production_start": date(2018, 11, 1), "production_end": None},
        {"model_name": "RAV4", "brand_name": "Toyota", "engine_capacity": 2.0, "engine_code": "3ZR-FE",
         "horsepower": 146, "production_start": date(2012, 12, 1), "production_end": date(2018, 10, 31)},
        {"model_name": "Civic", "brand_name": "Honda", "engine_capacity": 1.5, "engine_code": "L15B7",
         "horsepower": 174, "production_start": date(2016, 4, 1), "production_end": None},
        {"model_name": "Civic", "brand_name": "Honda", "engine_capacity": 2.0, "engine_code": "K20C2",
         "horsepower": 158, "production_start": date(2016, 4, 1), "production_end": None},
        {"model_name": "Civic", "brand_name": "Honda", "engine_capacity": 1.8, "engine_code": "R18Z1",
         "horsepower": 141, "production_start": date(2011, 9, 1), "production_end": date(2016, 3, 31)},
        {"model_name": "Accord", "brand_name": "Honda", "engine_capacity": 1.5, "engine_code": "L15BE",
         "horsepower": 192, "production_start": date(2017, 7, 1), "production_end": None},
        {"model_name": "Accord", "brand_name": "Honda", "engine_capacity": 2.0, "engine_code": "K20C4",
         "horsepower": 252, "production_start": date(2017, 7, 1), "production_end": None},
        {"model_name": "CR-V", "brand_name": "Honda", "engine_capacity": 1.5, "engine_code": "L15BE",
         "horsepower": 190, "production_start": date(2016, 9, 1), "production_end": None},
        {"model_name": "CR-V", "brand_name": "Honda", "engine_capacity": 2.4, "engine_code": "K24W",
         "horsepower": 184, "production_start": date(2011, 12, 1), "production_end": date(2016, 8, 31)},
        {"model_name": "X5", "brand_name": "BMW", "engine_capacity": 3.0, "engine_code": "B58B30",
         "horsepower": 335, "production_start": date(2018, 11, 1), "production_end": None},
        {"model_name": "X5", "brand_name": "BMW", "engine_capacity": 4.4, "engine_code": "N63B44",
         "horsepower": 456, "production_start": date(2018, 11, 1), "production_end": None},
        {"model_name": "X5", "brand_name": "BMW", "engine_capacity": 2.0, "engine_code": "B47D20",
         "horsepower": 231, "production_start": date(2013, 10, 1), "production_end": date(2018, 10, 31)},
        {"model_name": "3 Series", "brand_name": "BMW", "engine_capacity": 2.0, "engine_code": "B48B20",
         "horsepower": 255, "production_start": date(2018, 10, 1), "production_end": None},
        {"model_name": "3 Series", "brand_name": "BMW", "engine_capacity": 3.0, "engine_code": "B58B30",
         "horsepower": 382, "production_start": date(2018, 10, 1), "production_end": None},
        {"model_name": "5 Series", "brand_name": "BMW", "engine_capacity": 2.0, "engine_code": "B48B20",
         "horsepower": 248, "production_start": date(2016, 6, 1), "production_end": None},
        {"model_name": "5 Series", "brand_name": "BMW", "engine_capacity": 3.0, "engine_code": "B58B30",
         "horsepower": 335, "production_start": date(2016, 6, 1), "production_end": None},
        {"model_name": "C-Class", "brand_name": "Mercedes-Benz", "engine_capacity": 2.0, "engine_code": "M264",
         "horsepower": 255, "production_start": date(2018, 5, 1), "production_end": None},
        {"model_name": "C-Class", "brand_name": "Mercedes-Benz", "engine_capacity": 1.5, "engine_code": "M264",
         "horsepower": 181, "production_start": date(2018, 5, 1), "production_end": None},
        {"model_name": "C-Class", "brand_name": "Mercedes-Benz", "engine_capacity": 3.0, "engine_code": "M276",
         "horsepower": 362, "production_start": date(2014, 3, 1), "production_end": date(2018, 4, 30)},
        {"model_name": "E-Class", "brand_name": "Mercedes-Benz", "engine_capacity": 2.0, "engine_code": "M264",
         "horsepower": 255, "production_start": date(2016, 3, 1), "production_end": None},
        {"model_name": "E-Class", "brand_name": "Mercedes-Benz", "engine_capacity": 3.0, "engine_code": "M256",
         "horsepower": 362, "production_start": date(2016, 3, 1), "production_end": None},
        {"model_name": "Golf", "brand_name": "Volkswagen", "engine_capacity": 1.4, "engine_code": "CZDA",
         "horsepower": 147, "production_start": date(2017, 4, 1), "production_end": None},
        {"model_name": "Golf", "brand_name": "Volkswagen", "engine_capacity": 2.0, "engine_code": "EA888",
         "horsepower": 228, "production_start": date(2017, 4, 1), "production_end": None},
        {"model_name": "Golf", "brand_name": "Volkswagen", "engine_capacity": 1.2, "engine_code": "CJZA",
         "horsepower": 105, "production_start": date(2012, 11, 1), "production_end": date(2017, 3, 31)},
        {"model_name": "Passat", "brand_name": "Volkswagen", "engine_capacity": 1.8, "engine_code": "CPRA",
         "horsepower": 174, "production_start": date(2015, 8, 1), "production_end": None},
        {"model_name": "Passat", "brand_name": "Volkswagen", "engine_capacity": 2.0, "engine_code": "DSG",
         "horsepower": 220, "production_start": date(2015, 8, 1), "production_end": None},
        {"model_name": "Tiguan", "brand_name": "Volkswagen", "engine_capacity": 2.0, "engine_code": "EA888",
         "horsepower": 184, "production_start": date(2016, 5, 1), "production_end": None},
        {"model_name": "Tiguan", "brand_name": "Volkswagen", "engine_capacity": 1.4, "engine_code": "CZEA",
         "horsepower": 150, "production_start": date(2011, 5, 1), "production_end": date(2016, 4, 30)},
        {"model_name": "F-150", "brand_name": "Ford", "engine_capacity": 3.5, "engine_code": "EcoBoost",
         "horsepower": 375, "production_start": date(2017, 1, 1), "production_end": None},
        {"model_name": "F-150", "brand_name": "Ford", "engine_capacity": 5.0, "engine_code": "Coyote",
         "horsepower": 395, "production_start": date(2017, 1, 1), "production_end": None},
        {"model_name": "F-150", "brand_name": "Ford", "engine_capacity": 2.7, "engine_code": "EcoBoost",
         "horsepower": 325, "production_start": date(2014, 11, 1), "production_end": date(2017, 12, 31)},
        {"model_name": "Mustang", "brand_name": "Ford", "engine_capacity": 2.3, "engine_code": "EcoBoost",
         "horsepower": 310, "production_start": date(2014, 12, 1), "production_end": None},
        {"model_name": "Mustang", "brand_name": "Ford", "engine_capacity": 5.0, "engine_code": "Coyote",
         "horsepower": 460, "production_start": date(2014, 12, 1), "production_end": None},
        {"model_name": "Mustang", "brand_name": "Ford", "engine_capacity": 3.7, "engine_code": "Cyclone",
         "horsepower": 300, "production_start": date(2010, 4, 1), "production_end": date(2014, 11, 30)},
        {"model_name": "Tucson", "brand_name": "Hyundai", "engine_capacity": 2.0, "engine_code": "G4NC",
         "horsepower": 164, "production_start": date(2015, 9, 1), "production_end": None},
        {"model_name": "Tucson", "brand_name": "Hyundai", "engine_capacity": 1.6, "engine_code": "G4FJ",
         "horsepower": 177, "production_start": date(2015, 9, 1), "production_end": None},
        {"model_name": "Tucson", "brand_name": "Hyundai", "engine_capacity": 2.4, "engine_code": "G4KE",
         "horsepower": 182, "production_start": date(2009, 8, 1), "production_end": date(2015, 8, 31)},
        {"model_name": "Sonata", "brand_name": "Hyundai", "engine_capacity": 2.4, "engine_code": "G4KJ",
         "horsepower": 185, "production_start": date(2014, 6, 1), "production_end": None},
        {"model_name": "Sonata", "brand_name": "Hyundai", "engine_capacity": 2.0, "engine_code": "G4NA",
         "horsepower": 245, "production_start": date(2014, 6, 1), "production_end": None},
        {"model_name": "Sonata", "brand_name": "Hyundai", "engine_capacity": 2.0, "engine_code": "G4KD",
         "horsepower": 163, "production_start": date(2009, 6, 1), "production_end": date(2014, 5, 31)},
        {"model_name": "A4", "brand_name": "Audi", "engine_capacity": 2.0, "engine_code": "CJE",
         "horsepower": 252, "production_start": date(2015, 10, 1), "production_end": None},
        {"model_name": "A4", "brand_name": "Audi", "engine_capacity": 1.4, "engine_code": "CVN",
         "horsepower": 150, "production_start": date(2015, 10, 1), "production_end": None},
        {"model_name": "A4", "brand_name": "Audi", "engine_capacity": 3.0, "engine_code": "CREC",
         "horsepower": 333, "production_start": date(2012, 1, 1), "production_end": date(2015, 9, 30)},
        {"model_name": "Q5", "brand_name": "Audi", "engine_capacity": 2.0, "engine_code": "CJE",
         "horsepower": 252, "production_start": date(2016, 11, 1), "production_end": None},
        {"model_name": "Q5", "brand_name": "Audi", "engine_capacity": 3.0, "engine_code": "CTUC",
         "horsepower": 272, "production_start": date(2012, 6, 1), "production_end": date(2016, 10, 31)},
    ]
    for spec_data in specs:
        brand = Brand.objects.get(name=spec_data["brand_name"])
        model = Model.objects.get(name=spec_data["model_name"], brand=brand)
        # Use get to check for existing specifications before creating
        spec, created = ModelSpecification.objects.get_or_create(
            model=model,
            engine_code=spec_data["engine_code"],
            defaults={
                "engine_capacity": spec_data["engine_capacity"],
                "horsepower": spec_data["horsepower"],
                "production_start": spec_data["production_start"],
                "production_end": spec_data["production_end"],
            }
        )
        if not created and (
            spec.engine_capacity != spec_data["engine_capacity"] or
            spec.horsepower != spec_data["horsepower"] or
            spec.production_start != spec_data["production_start"] or
            spec.production_end != spec_data["production_end"]
        ):
            # Update existing specification if it differs
            spec.engine_capacity = spec_data["engine_capacity"]
            spec.horsepower = spec_data["horsepower"]
            spec.production_start = spec_data["production_start"]
            spec.production_end = spec_data["production_end"]
            spec.save()

    # Создание типов продуктов
    product_types = [
        {"name": "Масляный фильтр"},
        {"name": "Воздушный фильтр"},
        {"name": "Тормозные колодки"},
        {"name": "Свечи зажигания"},
        {"name": "Аккумулятор"},
        {"name": "Ремень ГРМ"},
        {"name": "Топливный фильтр"},
        {"name": "Салонный фильтр"},
        {"name": "Тормозные диски"},
        {"name": "Щётки стеклоочистителя"},
    ]
    for pt_data in product_types:
        ProductType.objects.get_or_create(name=pt_data["name"])

    # Создание складов
    warehouses = [
        {"name": "Главный склад"},
        {"name": "Склад №2"},
        {"name": "Склад №3"},
    ]
    for wh_data in warehouses:
        Warehouse.objects.get_or_create(name=wh_data["name"])

    # Создание продуктов
    products = [
        {
            "name": "Масляный фильтр Toyota Camry 2.5",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для Toyota Camry 2.5L",
            "cost_price": Decimal("500.00"),
            "selling_price": Decimal("700.00"),
            "quantity": 50,
            "specifications": [("Camry", "Toyota", "A25A-FKS")],
        },
        {
            "name": "Масляный фильтр Toyota Universal",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Универсальный для Toyota 2.0-3.5L",
            "cost_price": Decimal("300.00"),
            "selling_price": Decimal("450.00"),
            "quantity": 100,
            "specifications": [("Camry", "Toyota", "A25A-FKS"), ("Corolla", "Toyota", "M20A-FKS"), ("RAV4", "Toyota", "A25A-FXS")],
        },
        {
            "name": "Воздушный фильтр Honda Civic 1.5",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "CHINA",
            "comment": "Для Honda Civic 1.5L Turbo",
            "cost_price": Decimal("200.00"),
            "selling_price": Decimal("350.00"),
            "quantity": 30,
            "specifications": [("Civic", "Honda", "L15B7")],
        },
        {
            "name": "Тормозные колодки BMW X5",
            "product_type_name": "Тормозные колодки",
            "warehouse_name": "Главный склад",
            "origin": "USED",
            "comment": "Б/У колодки для BMW X5",
            "cost_price": Decimal("1000.00"),
            "selling_price": Decimal("1500.00"),
            "quantity": 10,
            "specifications": [("X5", "BMW", "B58B30")],
        },
        {
            "name": "Свечи зажигания Toyota Camry",
            "product_type_name": "Свечи зажигания",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Иридиевые свечи для Camry",
            "cost_price": Decimal("800.00"),
            "selling_price": Decimal("1200.00"),
            "quantity": 40,
            "specifications": [("Camry", "Toyota", "A25A-FKS"), ("Camry", "Toyota", "2GR-FKS")],
        },
        {
            "name": "Аккумулятор Mercedes C-Class",
            "product_type_name": "Аккумулятор",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "70Ah для Mercedes C-Class",
            "cost_price": Decimal("4000.00"),
            "selling_price": Decimal("5500.00"),
            "quantity": 15,
            "specifications": [("C-Class", "Mercedes-Benz", "M264")],
        },
        {
            "name": "Ремень ГРМ Volkswagen Golf",
            "product_type_name": "Ремень ГРМ",
            "warehouse_name": "Главный склад",
            "origin": "CHINA",
            "comment": "Для VW Golf 1.4 TSI",
            "cost_price": Decimal("600.00"),
            "selling_price": Decimal("900.00"),
            "quantity": 25,
            "specifications": [("Golf", "Volkswagen", "CZDA")],
        },
        {
            "name": "Топливный фильтр Ford F-150",
            "product_type_name": "Топливный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для Ford F-150 3.5L",
            "cost_price": Decimal("450.00"),
            "selling_price": Decimal("650.00"),
            "quantity": 35,
            "specifications": [("F-150", "Ford", "EcoBoost")],
        },
        {
            "name": "Салонный фильтр Hyundai Tucson",
            "product_type_name": "Салонный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "CHINA",
            "comment": "Угольный фильтр для Tucson",
            "cost_price": Decimal("250.00"),
            "selling_price": Decimal("400.00"),
            "quantity": 60,
            "specifications": [("Tucson", "Hyundai", "G4NC"), ("Tucson", "Hyundai", "G4FJ")],
        },
        {
            "name": "Тормозные диски Audi A4",
            "product_type_name": "Тормозные диски",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Передние диски для Audi A4",
            "cost_price": Decimal("3000.00"),
            "selling_price": Decimal("4500.00"),
            "quantity": 20,
            "specifications": [("A4", "Audi", "CJE")],
        },
        {
            "name": "Щётки стеклоочистителя BMW 3 Series",
            "product_type_name": "Щётки стеклоочистителя",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для BMW 3 Series",
            "cost_price": Decimal("700.00"),
            "selling_price": Decimal("1000.00"),
            "quantity": 50,
            "specifications": [("3 Series", "BMW", "B48B20"), ("3 Series", "BMW", "B58B30")],
        },
        {
            "name": "Масляный фильтр Honda Accord",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "CHINA",
            "comment": "Для Honda Accord 1.5-2.0L",
            "cost_price": Decimal("280.00"),
            "selling_price": Decimal("420.00"),
            "quantity": 45,
            "specifications": [("Accord", "Honda", "L15BE"), ("Accord", "Honda", "K20C4")],
        },
        {
            "name": "Воздушный фильтр VW Passat",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для VW Passat 1.8-2.0L",
            "cost_price": Decimal("350.00"),
            "selling_price": Decimal("500.00"),
            "quantity": 55,
            "specifications": [("Passat", "Volkswagen", "CPRA")],
        },
        {
            "name": "Тормозные колодки Ford Mustang",
            "product_type_name": "Тормозные колодки",
            "warehouse_name": "Склад №2",
            "origin": "USED",
            "comment": "Б/У для Ford Mustang",
            "cost_price": Decimal("800.00"),
            "selling_price": Decimal("1200.00"),
            "quantity": 12,
            "specifications": [("Mustang", "Ford", "EcoBoost")],
        },
        {
            "name": "Свечи зажигания Hyundai Sonata",
            "product_type_name": "Свечи зажигания",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для Hyundai Sonata 2.4L",
            "cost_price": Decimal("900.00"),
            "selling_price": Decimal("1300.00"),
            "quantity": 30,
            "specifications": [("Sonata", "Hyundai", "G4KJ")],
        },
        {
            "name": "Масляный фильтр Mercedes E-Class",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для Mercedes E-Class",
            "cost_price": Decimal("600.00"),
            "selling_price": Decimal("850.00"),
            "quantity": 40,
            "specifications": [("E-Class", "Mercedes-Benz", "M264"), ("E-Class", "Mercedes-Benz", "M256")],
        },
        {
            "name": "Воздушный фильтр Audi Q5",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Для Audi Q5 2.0L",
            "cost_price": Decimal("250.00"),
            "selling_price": Decimal("380.00"),
            "quantity": 70,
            "specifications": [("Q5", "Audi", "CJE")],
        },
        {
            "name": "Тормозные диски Toyota RAV4",
            "product_type_name": "Тормозные диски",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Передние диски для RAV4",
            "cost_price": Decimal("2500.00"),
            "selling_price": Decimal("3500.00"),
            "quantity": 15,
            "specifications": [("RAV4", "Toyota", "A25A-FXS")],
        },
        {
            "name": "Салонный фильтр BMW 5 Series",
            "product_type_name": "Салонный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "CHINA",
            "comment": "Угольный фильтр для BMW 5 Series",
            "cost_price": Decimal("300.00"),
            "selling_price": Decimal("450.00"),
            "quantity": 50,
            "specifications": [("5 Series", "BMW", "B48B20")],
        },
        {
            "name": "Топливный фильтр VW Tiguan",
            "product_type_name": "Топливный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для VW Tiguan 2.0L",
            "cost_price": Decimal("400.00"),
            "selling_price": Decimal("600.00"),
            "quantity": 25,
            "specifications": [("Tiguan", "Volkswagen", "EA888")],
        },
        {
            "name": "Масляный фильтр Ford F-150 5.0",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для Ford F-150 5.0L",
            "cost_price": Decimal("550.00"),
            "selling_price": Decimal("800.00"),
            "quantity": 35,
            "specifications": [("F-150", "Ford", "Coyote")],
        },
        {
            "name": "Воздушный фильтр Toyota Corolla",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "CHINA",
            "comment": "Для Toyota Corolla 1.8-2.0L",
            "cost_price": Decimal("180.00"),
            "selling_price": Decimal("300.00"),
            "quantity": 80,
            "specifications": [("Corolla", "Toyota", "2ZR-FE"), ("Corolla", "Toyota", "M20A-FKS")],
        },
        {
            "name": "Тормозные колодки Honda CR-V",
            "product_type_name": "Тормозные колодки",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для Honda CR-V",
            "cost_price": Decimal("1200.00"),
            "selling_price": Decimal("1800.00"),
            "quantity": 20,
            "specifications": [("CR-V", "Honda", "L15BE")],
        },
        {
            "name": "Свечи зажигания Audi A4",
            "product_type_name": "Свечи зажигания",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для Audi A4 1.4L",
            "cost_price": Decimal("850.00"),
            "selling_price": Decimal("1250.00"),
            "quantity": 30,
            "specifications": [("A4", "Audi", "CVN")],
        },
        {
            "name": "Аккумулятор VW Golf",
            "product_type_name": "Аккумулятор",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "60Ah для VW Golf",
            "cost_price": Decimal("3500.00"),
            "selling_price": Decimal("5000.00"),
            "quantity": 10,
            "specifications": [("Golf", "Volkswagen", "CZDA")],
        },
        {
            "name": "Ремень ГРМ Hyundai Tucson",
            "product_type_name": "Ремень ГРМ",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Для Hyundai Tucson 1.6L",
            "cost_price": Decimal("500.00"),
            "selling_price": Decimal("750.00"),
            "quantity": 40,
            "specifications": [("Tucson", "Hyundai", "G4FJ")],
        },
        {
            "name": "Топливный фильтр BMW X5",
            "product_type_name": "Топливный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для BMW X5 4.4L",
            "cost_price": Decimal("600.00"),
            "selling_price": Decimal("900.00"),
            "quantity": 15,
            "specifications": [("X5", "BMW", "N63B44")],
        },
        {
            "name": "Салонный фильтр Toyota Camry",
            "product_type_name": "Салонный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "CHINA",
            "comment": "Для Toyota Camry",
            "cost_price": Decimal("200.00"),
            "selling_price": Decimal("350.00"),
            "quantity": 60,
            "specifications": [("Camry", "Toyota", "A25A-FKS")],
        },
        {
            "name": "Тормозные диски Mercedes C-Class",
            "product_type_name": "Тормозные диски",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Задние диски для C-Class",
            "cost_price": Decimal("2800.00"),
            "selling_price": Decimal("4000.00"),
            "quantity": 12,
            "specifications": [("C-Class", "Mercedes-Benz", "M264")],
        },
        {
            "name": "Щётки стеклоочистителя Honda Civic",
            "product_type_name": "Щётки стеклоочистителя",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для Honda Civic",
            "cost_price": Decimal("650.00"),
            "selling_price": Decimal("900.00"),
            "quantity": 45,
            "specifications": [("Civic", "Honda", "L15B7")],
        },
        {
            "name": "Масляный фильтр Ford F-150 2.7",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для Ford F-150 2.7L",
            "cost_price": Decimal("520.00"),
            "selling_price": Decimal("750.00"),
            "quantity": 30,
            "specifications": [("F-150", "Ford", "EcoBoost")],
        },
        {
            "name": "Воздушный фильтр Audi A4",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Для Audi A4 3.0L",
            "cost_price": Decimal("250.00"),
            "selling_price": Decimal("400.00"),
            "quantity": 50,
            "specifications": [("A4", "Audi", "CREC")],
        },
        {
            "name": "Тормозные колодки Hyundai Sonata",
            "product_type_name": "Тормозные колодки",
            "warehouse_name": "Склад №3",
            "origin": "USED",
            "comment": "Б/У для Sonata",
            "cost_price": Decimal("900.00"),
            "selling_price": Decimal("1300.00"),
            "quantity": 20,
            "specifications": [("Sonata", "Hyundai", "G4KJ")],
        },
        {
            "name": "Свечи зажигания VW Tiguan",
            "product_type_name": "Свечи зажигания",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для VW Tiguan 1.4L",
            "cost_price": Decimal("800.00"),
            "selling_price": Decimal("1100.00"),
            "quantity": 25,
            "specifications": [("Tiguan", "Volkswagen", "CZEA")],
        },
        {
            "name": "Аккумулятор BMW 5 Series",
            "product_type_name": "Аккумулятор",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "70Ah для BMW 5 Series",
            "cost_price": Decimal("3800.00"),
            "selling_price": Decimal("5500.00"),
            "quantity": 10,
            "specifications": [("5 Series", "BMW", "B58B30")],
        },
        {
            "name": "Ремень ГРМ Toyota Corolla",
            "product_type_name": "Ремень ГРМ",
            "warehouse_name": "Склад №3",
            "origin": "CHINA",
            "comment": "Для Corolla 1.8L",
            "cost_price": Decimal("450.00"),
            "selling_price": Decimal("650.00"),
            "quantity": 35,
            "specifications": [("Corolla", "Toyota", "2ZR-FE")],
        },
        {
            "name": "Топливный фильтр Honda CR-V",
            "product_type_name": "Топливный фильтр",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для CR-V 2.4L",
            "cost_price": Decimal("400.00"),
            "selling_price": Decimal("600.00"),
            "quantity": 30,
            "specifications": [("CR-V", "Honda", "K24W")],
        },
        {
            "name": "Салонный фильтр Mercedes E-Class",
            "product_type_name": "Салонный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Для E-Class",
            "cost_price": Decimal("220.00"),
            "selling_price": Decimal("350.00"),
            "quantity": 50,
            "specifications": [("E-Class", "Mercedes-Benz", "M256")],
        },
        {
            "name": "Тормозные диски BMW X5",
            "product_type_name": "Тормозные диски",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Задние для BMW X5",
            "cost_price": Decimal("3200.00"),
            "selling_price": Decimal("4500.00"),
            "quantity": 15,
            "specifications": [("X5", "BMW", "B47D20")],
        },
        {
            "name": "Щётки стеклоочистителя Toyota Camry",
            "product_type_name": "Щётки стеклоочистителя",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Для Camry",
            "cost_price": Decimal("600.00"),
            "selling_price": Decimal("850.00"),
            "quantity": 40,
            "specifications": [("Camry", "Toyota", "2GR-FKS")],
        },
        {
            "name": "Масляный фильтр Honda Civic 1.8",
            "product_type_name": "Масляный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "CHINA",
            "comment": "Для Civic 1.8L",
            "cost_price": Decimal("200.00"),
            "selling_price": Decimal("300.00"),
            "quantity": 60,
            "specifications": [("Civic", "Honda", "R18Z1")],
        },
        {
            "name": "Воздушный фильтр VW Golf 1.2",
            "product_type_name": "Воздушный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "Для Golf 1.2 TSI",
            "cost_price": Decimal("400.00"),
            "selling_price": Decimal("600.00"),
            "quantity": 35,
            "specifications": [("Golf", "Volkswagen", "CJZA")],
        },
        {
            "name": "Тормозные колодки Audi Q5",
            "product_type_name": "Тормозные колодки",
            "warehouse_name": "Главный склад",
            "origin": "USED",
            "comment": "Б/У для Q5",
            "cost_price": Decimal("900.00"),
            "selling_price": Decimal("1300.00"),
            "quantity": 10,
            "specifications": [("Q5", "Audi", "CTUC")],
        },
        {
            "name": "Свечи зажигания Toyota RAV4",
            "product_type_name": "Свечи зажигания",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для RAV4 2.0L",
            "cost_price": Decimal("700.00"),
            "selling_price": Decimal("1000.00"),
            "quantity": 25,
            "specifications": [("RAV4", "Toyota", "3ZR-FE")],
        },
        {
            "name": "Аккумулятор Ford Mustang",
            "product_type_name": "Аккумулятор",
            "warehouse_name": "Склад №3",
            "origin": "ORIGINAL",
            "comment": "65Ah для Mustang",
            "cost_price": Decimal("3600.00"),
            "selling_price": Decimal("5200.00"),
            "quantity": 15,
            "specifications": [("Mustang", "Ford", "Cyclone")],
        },
        {
            "name": "Ремень ГРМ Honda Accord",
            "product_type_name": "Ремень ГРМ",
            "warehouse_name": "Главный склад",
            "origin": "CHINA",
            "comment": "Для Accord 2.0L",
            "cost_price": Decimal("550.00"),
            "selling_price": Decimal("800.00"),
            "quantity": 30,
            "specifications": [("Accord", "Honda", "K20C4")],
        },
        {
            "name": "Топливный фильтр Mercedes C-Class",
            "product_type_name": "Топливный фильтр",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для C-Class 3.0L",
            "cost_price": Decimal("350.00"),
            "selling_price": Decimal("500.00"),
            "quantity": 20,
            "specifications": [("C-Class", "Mercedes-Benz", "M276")],
        },
        {
            "name": "Салонный фильтр VW Passat",
            "product_type_name": "Салонный фильтр",
            "warehouse_name": "Склад №3",
            "origin": "CHINA",
            "comment": "Для Passat",
            "cost_price": Decimal("200.00"),
            "selling_price": Decimal("350.00"),
            "quantity": 50,
            "specifications": [("Passat", "Volkswagen", "CPRA")],
        },
        {
            "name": "Тормозные диски Hyundai Sonata",
            "product_type_name": "Тормозные диски",
            "warehouse_name": "Главный склад",
            "origin": "ORIGINAL",
            "comment": "Передние для Sonata",
            "cost_price": Decimal("2500.00"),
            "selling_price": Decimal("3500.00"),
            "quantity": 15,
            "specifications": [("Sonata", "Hyundai", "G4KD")],
        },
        {
            "name": "Щётки стеклоочистителя BMW 3 Series",
            "product_type_name": "Щётки стеклоочистителя",
            "warehouse_name": "Склад №2",
            "origin": "ORIGINAL",
            "comment": "Для 3 Series",
            "cost_price": Decimal("650.00"),
            "selling_price": Decimal("900.00"),
            "quantity": 40,
            "specifications": [("3 Series", "BMW", "B48B20")],
        },
    ]

    for product_data in products:
        product_type = ProductType.objects.get(name=product_data["product_type_name"])
        warehouse = Warehouse.objects.get(name=product_data["warehouse_name"])

        # Создание или получение продукта
        product, created = Product.objects.get_or_create(
            name=product_data["name"],
            product_type=product_type,
            warehouse=warehouse,
            defaults={
                "origin": product_data["origin"],
                "comment": product_data["comment"],
                "cost_price": product_data["cost_price"],
                "selling_price": product_data["selling_price"],
                "quantity": product_data["quantity"],
            }
        )

        # Добавление спецификаций
        for spec_data in product_data["specifications"]:
            try:
                model_name, brand_name, engine_code = spec_data
                brand = Brand.objects.get(name=brand_name)
                model = Model.objects.get(name=model_name, brand=brand)
                spec = ModelSpecification.objects.get(model=model, engine_code=engine_code)
                product.specifications.add(spec)
            except (Brand.DoesNotExist, Model.DoesNotExist, ModelSpecification.DoesNotExist) as e:
                print(f"Ошибка при добавлении спецификации для {product_data['name']}: {e}")

    print("База данных успешно заполнена!")

if __name__ == "__main__":
    seed_db()